version: '2'
services:
  wordpress:
    image: wordpress:5.2.1
    depends_on:
      - mysql
    ports:
      - "80:80"
    restart: always
    environment:
      - WORDPRESS_DB_NAME=codespa
      - WORDPRESS_DB_USER=root
    volumes:
      - ./www/themes:/var/www/html/wp-content/themes        # Themes subdirectory
      - ./www/plugins:/var/www/html/wp-content/plugins      # Plugins subdirectory


  mysql:
    image: mysql:5.7
    volumes:
       - ./data/mysql:/var/lib/mysql
       - ./data-dump/wordpress.sql:/docker-entrypoint-initdb.d/wordpress.sql  # Trying to import data
    restart: always
    environment:
      - MYSQL_DATABASE=codespa
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'



